use clap::{Parser, Subcommand};
use chrono::Utc;
use std::env;
use std::path::PathBuf;
use tidyflow_core::workspace::{AppState, ProjectManager, StateStore, WorkspaceManager};
use tracing::info;

/// 默认端口：开发环境 3439，生产环境 8439
fn default_port() -> u16 {
    if env::var("TIDYFLOW_DEV").is_ok() {
        3439
    } else {
        8439
    }
}

#[derive(Parser)]
#[command(name = "tidyflow-core")]
#[command(about = "TidyFlow Core - Terminal and Workspace Engine")]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum Commands {
    /// Start the WebSocket server (default)
    Serve {
        #[arg(short, long)]
        port: Option<u16>,
        /// Bind address for WebSocket/HTTP server (default: 127.0.0.1)
        #[arg(long)]
        bind_addr: Option<String>,
    },
    /// Import a project
    Import {
        /// Project name
        #[arg(long)]
        name: String,
        /// Local path to import
        #[arg(long, conflicts_with = "git")]
        path: Option<PathBuf>,
        /// Git URL to clone
        #[arg(long, conflicts_with = "path")]
        git: Option<String>,
        /// Branch to clone (for git import)
        #[arg(long)]
        branch: Option<String>,
    },
    /// Workspace operations
    Ws {
        #[command(subcommand)]
        action: WsCommands,
    },
    /// List projects or workspaces
    List {
        #[command(subcommand)]
        what: ListCommands,
    },
}

#[derive(Subcommand)]
enum WsCommands {
    /// Create a new workspace (name auto-generated by Core)
    Create {
        /// Project name
        #[arg(long)]
        project: String,
        /// Source branch
        #[arg(long)]
        from_branch: Option<String>,
        /// Skip setup
        #[arg(long)]
        no_setup: bool,
    },
    /// Show workspace details
    Show {
        /// Project name
        #[arg(long)]
        project: String,
        /// Workspace name
        #[arg(long)]
        workspace: String,
    },
    /// Run setup for a workspace
    Setup {
        /// Project name
        #[arg(long)]
        project: String,
        /// Workspace name
        #[arg(long)]
        workspace: String,
    },
    /// Remove a workspace
    Remove {
        /// Project name
        #[arg(long)]
        project: String,
        /// Workspace name
        #[arg(long)]
        workspace: String,
    },
}

#[derive(Subcommand)]
enum ListCommands {
    /// List all projects
    Projects,
    /// List workspaces for a project
    Workspaces {
        /// Project name
        #[arg(long)]
        project: String,
    },
}

fn parse_env_port() -> Option<u16> {
    env::var("TIDYFLOW_PORT")
        .ok()
        .and_then(|p| p.parse::<u16>().ok())
}

fn sanitize_bind_addr(value: Option<String>) -> Option<String> {
    value
        .map(|addr| addr.trim().to_string())
        .filter(|addr| !addr.is_empty())
}

async fn resolve_server_port_and_bind(
    cli_port: Option<u16>,
    cli_bind_addr: Option<String>,
    state_store: &StateStore,
) -> (u16, String) {
    let state = state_store.load().await.unwrap_or_default();
    let fixed_port = state.client_settings.fixed_port;
    let remote_access_enabled = state.client_settings.remote_access_enabled;

    let port = cli_port
        .or_else(parse_env_port)
        .or_else(|| {
            if fixed_port > 0 {
                Some(fixed_port)
            } else {
                None
            }
        })
        .unwrap_or_else(default_port);

    let bind_addr = sanitize_bind_addr(cli_bind_addr)
        .or_else(|| sanitize_bind_addr(env::var("TIDYFLOW_BIND_ADDR").ok()))
        .unwrap_or_else(|| {
            if remote_access_enabled {
                "0.0.0.0".to_string()
            } else {
                "127.0.0.1".to_string()
            }
        });

    (port, bind_addr)
}

async fn persist_state(store: &StateStore, state: &mut AppState) -> Result<(), Box<dyn std::error::Error>> {
    state.last_updated = Some(Utc::now());
    store.save(state).await?;
    Ok(())
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tidyflow_core::util::init_logging();

    let cli = Cli::parse();

    match cli.command {
        None | Some(Commands::Serve { .. }) => {
            let state_store = StateStore::open_default().await?;
            let (port, bind_addr) = match &cli.command {
                Some(Commands::Serve { port, bind_addr }) => {
                    resolve_server_port_and_bind(*port, bind_addr.clone(), &state_store).await
                }
                _ => resolve_server_port_and_bind(None, None, &state_store).await,
            };
            env::set_var("TIDYFLOW_BIND_ADDR", bind_addr);
            info!("Starting TidyFlow Core server on port {}", port);
            tidyflow_core::server::run_server(port).await?;
        }
        Some(Commands::Import {
            name,
            path,
            git,
            branch,
        }) => {
            let state_store = StateStore::open_default().await?;
            let mut state = state_store.load().await?;

            if let Some(local_path) = path {
                let project = ProjectManager::import_local(&mut state, &name, &local_path)?;
                persist_state(&state_store, &mut state).await?;
                println!("Project imported: {}", project.name);
                println!("  Path: {}", project.root_path.display());
                println!("  Branch: {}", project.default_branch);
            } else if let Some(url) = git {
                let project =
                    ProjectManager::import_git(&mut state, &name, &url, branch.as_deref(), None)?;
                persist_state(&state_store, &mut state).await?;
                println!("Project cloned and imported: {}", project.name);
                println!("  Path: {}", project.root_path.display());
                println!("  Branch: {}", project.default_branch);
            } else {
                eprintln!("Error: Either --path or --git must be specified");
                std::process::exit(1);
            }
        }
        Some(Commands::Ws { action }) => match action {
            WsCommands::Create {
                project,
                from_branch,
                no_setup,
            } => {
                let state_store = StateStore::open_default().await?;
                let mut state = state_store.load().await?;
                let ws = WorkspaceManager::create(
                    &mut state,
                    &project,
                    from_branch.as_deref(),
                    !no_setup,
                )?;
                persist_state(&state_store, &mut state).await?;
                println!("Workspace created: {}", ws.name);
                println!("  Path: {}", ws.worktree_path.display());
                println!("  Branch: {}", ws.branch);
                println!("  Status: {:?}", ws.status);
            }
            WsCommands::Show { project, workspace } => {
                let state_store = StateStore::open_default().await?;
                let state = state_store.load().await?;
                let path = WorkspaceManager::get_root_path(&state, &project, &workspace)?;

                let proj = state.get_project(&project).unwrap();
                let ws = proj.get_workspace(&workspace).unwrap();

                println!("{}", path.display());
                // Additional info to stderr so stdout is just the path
                eprintln!("---");
                eprintln!("Project: {}", project);
                eprintln!("Workspace: {}", workspace);
                eprintln!("Branch: {}", ws.branch);
                eprintln!("Status: {:?}", ws.status);
                if let Some(ref result) = ws.setup_result {
                    eprintln!(
                        "Setup: {}/{} steps completed",
                        result.steps_completed, result.steps_total
                    );
                }
            }
            WsCommands::Setup { project, workspace } => {
                let state_store = StateStore::open_default().await?;
                let mut state = state_store.load().await?;
                let ws = WorkspaceManager::run_setup(&mut state, &project, &workspace)?;
                persist_state(&state_store, &mut state).await?;
                println!("Setup completed for workspace: {}", ws.name);
                println!("  Status: {:?}", ws.status);
                if let Some(ref result) = ws.setup_result {
                    println!("  Steps: {}/{}", result.steps_completed, result.steps_total);
                    if let Some(ref err) = result.last_error {
                        println!("  Last error: {}", err);
                    }
                }
            }
            WsCommands::Remove { project, workspace } => {
                let state_store = StateStore::open_default().await?;
                let mut state = state_store.load().await?;
                WorkspaceManager::remove(&mut state, &project, &workspace)?;
                persist_state(&state_store, &mut state).await?;
                println!("Workspace removed: {}", workspace);
            }
        },
        Some(Commands::List { what }) => match what {
            ListCommands::Projects => {
                let state_store = StateStore::open_default().await?;
                let state = state_store.load().await?;
                let projects = state.list_projects();
                if projects.is_empty() {
                    println!("No projects imported");
                } else {
                    println!("Projects:");
                    for name in projects {
                        let proj = state.get_project(name).unwrap();
                        println!("  {} ({})", name, proj.root_path.display());
                    }
                }
            }
            ListCommands::Workspaces { project } => {
                let state_store = StateStore::open_default().await?;
                let state = state_store.load().await?;
                let proj = state
                    .get_project(&project)
                    .ok_or_else(|| format!("Project not found: {}", project))?;

                let workspaces = proj.list_workspaces();
                if workspaces.is_empty() {
                    println!("No workspaces for project: {}", project);
                } else {
                    println!("Workspaces for {}:", project);
                    for name in workspaces {
                        let ws = proj.get_workspace(name).unwrap();
                        println!(
                            "  {} [{:?}] -> {}",
                            name,
                            ws.status,
                            ws.worktree_path.display()
                        );
                    }
                }
            }
        },
    }

    Ok(())
}
