use axum::{
    routing::{delete, get, post},
    Router,
};

use super::context::AppContext;

pub(in crate::server::ws) fn build_router(ctx: AppContext) -> Router {
    Router::new()
        .route(
            "/ws",
            get(crate::server::ws::transport::endpoint::ws_handler),
        )
        .route(
            "/auth/keys",
            get(crate::server::ws::auth_keys::list_api_keys_handler),
        )
        .route(
            "/auth/keys",
            post(crate::server::ws::auth_keys::create_api_key_handler),
        )
        .route(
            "/auth/keys/:key_id",
            delete(crate::server::ws::auth_keys::delete_api_key_handler),
        )
        .route("/api/v1/projects", get(crate::server::ws::http_api::projects_handler))
        .route(
            "/api/v1/projects/:project/workspaces",
            get(crate::server::ws::http_api::workspaces_handler),
        )
        .route("/api/v1/tasks", get(crate::server::ws::http_api::tasks_handler))
        .route(
            "/api/v1/client-settings",
            get(crate::server::ws::http_api::client_settings_handler),
        )
        .route(
            "/api/v1/templates",
            get(crate::server::ws::http_api::templates_handler),
        )
        .route(
            "/api/v1/templates/:template_id/export",
            get(crate::server::ws::http_api::template_export_handler),
        )
        .route(
            "/api/v1/terminals",
            get(crate::server::ws::http_api::terminals_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/files",
            get(crate::server::ws::http_api::file_list_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/files/index",
            get(crate::server::ws::http_api::file_index_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/files/content",
            get(crate::server::ws::http_api::file_content_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/git/status",
            get(crate::server::ws::http_api::git_status_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/git/diff",
            get(crate::server::ws::http_api::git_diff_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/git/branches",
            get(crate::server::ws::http_api::git_branches_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/git/log",
            get(crate::server::ws::http_api::git_log_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/git/commits/:sha",
            get(crate::server::ws::http_api::git_commit_show_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/git/op-status",
            get(crate::server::ws::http_api::git_op_status_handler),
        )
        .route(
            "/api/v1/projects/:project/git/integration-status",
            get(crate::server::ws::http_api::git_integration_status_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/git/up-to-date",
            get(crate::server::ws::http_api::git_check_branch_up_to_date_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/git/conflicts/detail",
            get(crate::server::ws::http_api::git_conflict_detail_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/sessions",
            get(crate::server::ws::http_api::ai_sessions_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/:ai_tool/sessions/:session_id/messages",
            get(crate::server::ws::http_api::ai_session_messages_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/:ai_tool/sessions/:session_id/status",
            get(crate::server::ws::http_api::ai_session_status_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/:ai_tool/providers",
            get(crate::server::ws::http_api::ai_provider_list_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/:ai_tool/agents",
            get(crate::server::ws::http_api::ai_agent_list_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/:ai_tool/slash-commands",
            get(crate::server::ws::http_api::ai_session_slash_commands_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/:ai_tool/session-config-options",
            get(crate::server::ws::http_api::ai_session_config_options_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/:ai_tool/sessions/:session_id/context-snapshot",
            get(crate::server::ws::http_api::ai_session_context_snapshot_handler),
        )
        .route(
            "/api/v1/projects/:project/workspaces/:workspace/ai/context-snapshots",
            get(crate::server::ws::http_api::ai_cross_context_snapshots_handler),
        )
        .route(
            "/api/v1/evolution/snapshot",
            get(crate::server::ws::http_api::evolution_snapshot_handler),
        )
        .route(
            "/api/v1/evolution/projects/:project/workspaces/:workspace/agent-profile",
            get(crate::server::ws::http_api::evolution_agent_profile_handler),
        )
        .route(
            "/api/v1/evolution/projects/:project/workspaces/:workspace/cycle-history",
            get(crate::server::ws::http_api::evolution_cycle_history_handler),
        )
        .route(
            "/api/v1/evidence/projects/:project/workspaces/:workspace/snapshot",
            get(crate::server::ws::http_api::evidence_snapshot_handler),
        )
        .route(
            "/api/v1/evidence/projects/:project/workspaces/:workspace/rebuild-prompt",
            get(crate::server::ws::http_api::evidence_rebuild_prompt_handler),
        )
        .route(
            "/api/v1/evidence/projects/:project/workspaces/:workspace/items/:item_id/chunk",
            get(crate::server::ws::http_api::evidence_item_chunk_handler),
        )
        .route(
            "/api/v1/system/snapshot",
            get(crate::server::ws::http_api::system_snapshot_handler),
        )
        .route(
            "/api/v1/system/health",
            get(crate::server::ws::http_api::system_health_snapshot_handler),
        )
        .route(
            "/api/v1/system/repair",
            axum::routing::post(crate::server::ws::http_api::system_repair_handler),
        )
        .with_state(ctx)
}
